/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:d55eb534-0233-48f6-a7b4-801150a084d8",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_0Gq2BClwv",
    "aws_user_pools_web_client_id": "7dialvudgptap7uuuqu5u84r29",
    "oauth": {
        "domain": "whatsappcloneb5b58018-b5b58018-dev.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/,exp://192.168.0.3:19000/--/,http://localhost:3000/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/,exp://192.168.0.3:19000/--/,http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://3rhw5oayhnfblavlahd5krwvym.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "whatsappclone70d7e982c0f048879614689ef7f5ac8d211628-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
